language: python

# Use container-based infrastructure
sudo: false


python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - 3.6

# Do not use these credentials in your project
# Get a free account at https://urs.earthdata.nasa.gov/users/new
env:
 - SRTMEDUser=srtmpyuser SRTMEDPass=Srtm.py1

install:
 - pip install requests
 - pip install coverage

script:
 - coverage run --source=srtm ./test.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pyflakes pycodestyle
 - pyflakes . | tee >(wc -l)
 - pycodestyle --statistics --count .
